### PR TITLE
Added two new constructors

### PR DESCRIPTION
**Pull request by striderxfossility**
Vector4 and Quaternion

Signed-off-by: striderxfossility <jellebakker15@live.nl>

YEAH i did a pull request, awesome

### CODE REVIEW

**Comment by jac3km4** [comment]
I think those constructors should accept `number` instead of `Float`, so that users don't have to use wrappers.

**Comment by jac3km4** [comment]
Also, I'm pretty sure those types already exist in `cyberpunk.d.ts`, so we should probably add these constructors there.

**Comment by striderxfossility** [comment]
You mean like this:
declare interface Vector4 {
  /** @noSelf **/
  New(x: number, y: number, z: number, w: number): Vector4

**Comment by jac3km4** [comment]
I think we can change `declare interface` to `declare class` there and keep it a regular constructor.

**Review by jac3km4 — APPROVED** [review]

**Pull request merged**
